# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iTourism' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iTourism

  target 'iTourismTests' do
    inherit! :search_paths
    # Pods for testing
	pod 'RxSwift',        '~> 4.0'
	pod 'RxCocoa',        '~> 4.0'
	pod 'Alamofire',      '~> 4.5'
	pod 'RxAlamofire',    '~> 4.0'
	pod 'AlamofireImage', '~> 3.3'
	pod 'ObjectMapper',   '~> 3.1'

  end

  target 'iTourismUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
